services:
  - type: web
    name: payload-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URI
        value: postgres://postgres:cLdBe7jfkhAlOhvx@pjsofefgdbrqmtcbvwco.supabase.co:5432/postgres
      - key: PAYLOAD_SECRET
        value: your-secret-key-change-this
      - key: PAYLOAD_CONFIG_PATH
        value: src/payload.config.ts
      - key: NEXT_PUBLIC_SERVER_URL
        fromService:
          name: payload-app
          type: web
          property: url
